language: go

go:
  - 1.13.5

branches:
  only:
    - blog

install:
  - go get -tags extended github.com/gohugoio/hugo

script:
  - hugo

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: blog
