language: minimal

os: linux

branches:
  only:
    - blog

addons:
  snaps:
    - name: hugo
      channel: extended

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: public
  target_branch: master
  token: $GITHUB_TOKEN
  on:
    branch: blog
