language: go

go:
  - 1.13.5

os: linux

branches:
  only:
    - blog

install:
  - go get -tags extended github.com/gohugoio/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: public
  target_branch: master
  token: $GITHUB_TOKEN
  on:
    branch: blog
